# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-31 15:03
from __future__ import unicode_literals

from django.db import migrations
import tmqr_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('tmqr_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='insruments_list',
            field=tmqr_backend.models.SeparatedValuesField(default=''),
        ),
    ]
